server:
  port: 8001

spring:
  application:
    name: payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=true&useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.szy.pojo

feign:
  hystrix:
    enabled: true